//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyral.KeyboardSpamDetector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyral.KeyboardSpamDetector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 314080:1210736
        ///a,a,8
        ///a,b,3238
        ///a,c,4477
        ///a,d,5085
        ///a,e,122
        ///a,f,876
        ///a,g,2740
        ///a,h,143
        ///a,i,4973
        ///a,j,119
        ///a,k,1708
        ///a,l,11759
        ///a,m,3191
        ///a,n,24677
        ///a,o,33
        ///a,p,2501
        ///a,q,4
        ///a,r,13308
        ///a,s,12236
        ///a,t,16980
        ///a,u,1422
        ///a,v,3051
        ///a,w,1003
        ///a,x,87
        ///a,y,3120
        ///a,z,235
        ///b,a,1922
        ///b,b,277
        ///b,c,8
        ///b,d,11
        ///b,e,7961
        ///b,f,0
        ///b,g,0
        ///b,h,5
        ///b,i,933
        ///b,j,219
        ///b,k,0
        ///b,l,3344
        ///b,m,14
        ///b,n,5
        ///b,o,3682
        ///b,p,1
        ///b,q,0
        ///b,r,1404
        ///b,s,406
        ///b,t,235
        ///b,u,3379
        ///b,v,131
        ///b,w,3
        ///b,x,0
        ///b,y,1907
        ///b,z,0
        ///c,a,5489
        ///c,b,2
        ///c,c,686
        ///c,d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string occurences {
            get {
                return ResourceManager.GetString("occurences", resourceCulture);
            }
        }
    }
}
